token ::= ID | INT_LITERAL | FLOAT_LITERAL | CHAR_LITERAL | STRING_LITERAL
        | keyword | operator | delimiter

keyword ::= 'int' | 'float' | 'char' | 'bool' | 'void'
          | 'struct' | 'typedef'
          | 'if' | 'else'
          | 'while' | 'for' | 'do'
          | 'break' | 'continue' | 'return'
          | 'true' | 'false'
          | 'func'

operator ::= '==' | '!=' | '<=' | '>=' | '&&' | '||'
           | '+=' | '-=' | '*=' | '/='
           | '+' | '-' | '*' | '/' | '%'
           | '<' | '>' | '!' | '='

delimiter ::= '(' | ')' | '{' | '}' | '[' | ']' | ';' | ',' | '.'

FLOAT_LITERAL ::= digit+ '.' digit+ ( ('e' | 'E') ('+' | '-')? digit+ )?

INT_LITERAL ::= '0' ('x' | 'X') hexa+
              | '0' ('b' | 'B') bin+
              | digit+

CHAR_LITERAL ::= "'" ( escape | [^\\'] ) "'"
STRING_LITERAL ::= '"' ( escape | [^\\"] )* '"'
escape ::= '\\' .

ID ::= id_start id_cont*
id_start ::= letter | '_'
id_cont ::= letter | digit | '_'

letter ::= [a-zA-Z]
digit ::= [0-9]
hexa ::= [0-9a-fA-F]
bin ::= [01]

comment ::= block_comment | line_comment
block_comment ::= '/*' (. | newline)* '*/'
line_comment ::= '//' [^\n]*

whitespace ::= ' ' | '\t' | '\r' | newline
newline ::= '\n'+